"""Add can_edit to staff_users

Revision ID: 82fe1c0c0482
Revises: 686c8faa7336
Create Date: 2026-07-28 19:31:46.649986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '82fe1c0c0482'
down_revision: Union[str, None] = '686c8faa7336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_users', sa.Column('can_edit', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('staff_users', sa.Column('can_edit_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    op.execute("""
        CREATE OR REPLACE FUNCTION auth.list_org_staff(p_org_id UUID)
        RETURNS TABLE (id UUID, email TEXT, role TEXT, can_edit BOOLEAN, can_edit_until TIMESTAMPTZ, created_at TIMESTAMPTZ)
        LANGUAGE sql
        SECURITY DEFINER
        SET search_path = public
        AS $$
            SELECT id, email, role, can_edit, can_edit_until, created_at
            FROM   staff_users
            WHERE  org_id = p_org_id
            ORDER BY created_at ASC;
        $$
    """)
    op.execute("""
        CREATE OR REPLACE FUNCTION auth.update_staff_permissions(
            p_org_id UUID,
            p_user_id UUID,
            p_can_edit BOOLEAN,
            p_can_edit_until TIMESTAMPTZ
        )
        RETURNS VOID
        LANGUAGE sql
        SECURITY DEFINER
        SET search_path = public
        AS $$
            UPDATE staff_users
            SET    can_edit = p_can_edit,
                   can_edit_until = p_can_edit_until
            WHERE  org_id = p_org_id
            AND    id = p_user_id;
        $$
    """)
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'tapply_app') THEN
                GRANT EXECUTE ON FUNCTION auth.list_org_staff(UUID) TO tapply_app;
                REVOKE EXECUTE ON FUNCTION auth.list_org_staff(UUID) FROM PUBLIC;

                GRANT EXECUTE ON FUNCTION auth.update_staff_permissions(UUID, UUID, BOOLEAN, TIMESTAMPTZ) TO tapply_app;
                REVOKE EXECUTE ON FUNCTION auth.update_staff_permissions(UUID, UUID, BOOLEAN, TIMESTAMPTZ) FROM PUBLIC;
            END IF;
        END
        $$
    """)


def downgrade() -> None:
    op.execute("DROP FUNCTION IF EXISTS auth.update_staff_permissions(UUID, UUID, BOOLEAN, TIMESTAMPTZ)")
    op.execute("DROP FUNCTION IF EXISTS auth.list_org_staff(UUID)")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_users', 'can_edit_until')
    op.drop_column('staff_users', 'can_edit')
    # ### end Alembic commands ###
