"""
app/models/card.py
──────────────────
A physical NFC card or QR code attached to a Stand.

Token design:
  - Generated by the application layer using ``secrets.token_urlsafe(16)``
    at insert time (not a DB default), ensuring cryptographic randomness and
    URL-safe characters with no sequential pattern.
  - Minimum effective entropy: 16 bytes → 128 bits → 22 URL-safe characters.
  - Stored in a UNIQUE index; the public form endpoint looks cards up by token.

RLS note:
  Cards have no ``org_id`` column.  Their RLS policy is a join-based subquery:
      stand_id IN (SELECT id FROM stands WHERE org_id = current_setting(...)::uuid)
  This is slightly heavier than a direct column match but correct and safe.
"""

import uuid

from sqlalchemy import ForeignKey, Text, UniqueConstraint, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class Card(Base):
    __tablename__ = "cards"
    __table_args__ = (
        UniqueConstraint("token", name="uq_cards_token"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    stand_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("stands.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    token: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        doc=(
            "URL-safe random token used as the public card identifier. "
            "Generated via secrets.token_urlsafe(16) — never sequential."
        ),
    )
    is_active: Mapped[bool] = mapped_column(
        nullable=False,
        server_default=text("true"),
    )
    assigned_recruiter_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("staff_users.id", ondelete="SET NULL"),
        nullable=True,
    )

    def __repr__(self) -> str:
        return f"<Card id={self.id} token={self.token!r}>"
